project:
  type: website

website:
  title: "R中心生活"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tenomoto
      - icon: twitter
        href: https://twitter.com/takeshi_enomoto
format:
  html:
    theme: cosmo
    css: styles.css